### ISSUE TITLE
I don't understand what this is

### ISSUE THREAD

**Issue by chenfanfang** [yanagiba/swift-ast#110]
Hi, have a question

<img width="1369" alt="iShot_2022-11-09_16 28 05" src="https://user-images.githubusercontent.com/13808962/200778644-4896ce75-faaa-4177-bdaa-cad0ff99deb2.png">

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
