### ISSUE TITLE
Swift comments are not output by the visitors

### ISSUE THREAD

**Issue by corliss** [yanagiba/swift-ast#59]
Hi, it appears that swift comments (and also whitespace) are just ignored by the various visitors, e.g. `swift-ast -print-ast filename`. This makes it unusable as a simple swift-to-other-language translator, which is a stated goal of the project.

How can I enable comments to be included in the output?
Thanks.

**Comment by ryuichis** [comment]
Hi @corliss, comments and whitespaces are not part of the AST, so you can't use visitor to traverse it. However, the comment content and locations can be retrieved by `topLevelDeclaration.comments` (https://github.com/yanagiba/swift-ast/blob/master/Sources/AST/TopLevelDeclaration.swift#L21). There is currently no easy way to restore the whitespaces, but you might be able to calculate them by subtracting the node source range and comments range.

We acknowledged its inconvenience, so @angelolloqui and I are working towards a better way to expose the comments and whitespaces for code transformation.

On another note, if your tool *only* requires the high-level syntax of the Swift language, I suggest you look into Apple's intuitive https://github.com/apple/swift/tree/master/tools/SwiftSyntax started 3 months ago. The transformation we will achieve here in this project is to translate the semantics of the language, instead of token replacement, if that makes sense.
