### ISSUE TITLE
'postfix' as constant/variable name doesn't work

### ISSUE THREAD

**Issue by keeptyping** [yanagiba/swift-ast#62]
### Issue Summary
'postfix' as constant/variable name doesn't work.

### Environment
- OS Info: macOS Version 10.13.1 (Build 17B48)
- Yanagiba/swift-ast version: 0.4.1

### Reproduction Steps
Every constant/variable named 'postfix' is treated as an error. 

<details>
<summary>Sample code</summary>

```

struct PostfixIssue {
    
    private let postfix = ""
    
}

```

Command to run `swift-ast` with the code above:
`swift-ast PostfixIssue.swift`

</details>

### Expected Result
A successfully parsed TopLevelDeclaration.

### Actual Behavior
The parser failed with an expectedPattern error.

```
PostfixIssue.swift:13:17 fatal: expectedPattern
```

**Comment by ryuichis** [comment]
Hi @keeptyping, this is a good one. We are working towards the context-aware keywords - instead of the global keyword as in our current implementation, we will make the identifier understands its current context, and behave like a keyword or symbol accordingly.

Before that happens, I will try to patch a quick fix to unblock you, but hopefully we can ship the new way of handling keywords soon to solve this category of issues altogether.
