### ISSUE TITLE
Feature Request: ability to output into parsable format?

### ISSUE THREAD

**Issue by bagipro** [yanagiba/swift-ast#85]
Hi, I played with ``` swift-ast ```, but I don't see any way to somehow parse AST output. Is there an option to dump e.g. json of AST? Thanks

**Comment by ryuichis** [comment]
Maybe someone can leverage https://github.com/yanagiba/swift-transform and work on conversations to perhaps XML and/or json?

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
