### ISSUE TITLE
How to get the data type of variable?

### ISSUE THREAD

**Issue by zjzh** [yanagiba/swift-ast#99]
### Issue Summary
Dear people, I want to get the data type of swift source code, but it's seems difficult if don't use swift intermediate code. If exists a tool can convieniently get data type  or some solutions to get data type of swift source code 
        
The issue has same issue.
#19 @yanagiba @ryuichis

Thank you

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
